# Generated by Django 5.1 on 2024-09-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
