# Generated by Django 5.1 on 2024-09-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_brand_product_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='My Website', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
            ],
        ),
    ]
